data:
  _target_: training.dataset.DarkMatterZCond
  root: /srv/tmp/brandon/pm_dataset_planes_3
  normalize: True

model:
  _target_: models.precond.VPPrecond
  model_type: SongUNet
  img_resolution: 128
  img_channels: 1
  label_dim: 20
  model_channels: 128
  channel_mult: [1,2,2]
  attn_resolutions: [16]
  num_blocks: 1
  dropout: 0.0

loss:
  _target_: training.loss.VPLoss

train:
  lr: 0.0001
  batch_size: 64
  num_steps: 100_000
  warmup_steps: 500
  ema_decay: 0.9999
  grad_clip: 0.0
  ema_halflife_nimg: 209600
  ema_rampup_ratio: 0.05
  tf32: True
  resume: None
  num_workers: 4

diffusion_scheduler_config:
  num_steps: 5
  sigma_min: 0.01
  sigma_final: 0
  schedule: 'linear'
  timestep: 'poly-7'

log:
  exp_dir: 'exps/pretrain'
  exp_name: test
  wandb: True
  project: 'darkmatter-prior'
  group: 'training'
  log_every: 50
  save_every: 5000
