name: DAPS
method:
  _target_: algo.daps.DAPS
  annealing_scheduler_config:
    num_steps: 200
    sigma_max: 100
    sigma_min: 0.1
    sigma_final: 0
    schedule: 'linear'
    timestep: 'poly-7'

  diffusion_scheduler_config:
    num_steps: 15
    sigma_min: 1e-4
    sigma_final: 0
    schedule: 'linear'
    timestep: 'poly-7'

  lgvd_config:
    num_steps: 100
    lr: 1e-4
    tau: 5e-4 #smaller = more likelihood
    lr_min_ratio: 0.01
